sock 多次建联, 导致tcp连接占用涨满
weibocom/motan-openresty pull request #5
Opened 2018-09-27 07:11 UTC by yangjian5

现象，大量的tcp连接占用。 导致抛出 not assign requested address
利用 motan debug 模式发现 motan endpoint failed connect to peer: socket connection error

2019-02-22 15:48 UTC, idevz commented
多次建连是因为当连接成功后，并没有直接返回，而是在函数末尾又建立一次连接，但是当建连失败的时候，Mesh 场景下，应该读取快照进行直连，非 Mesh 场景下，应该对该节点进行一次重试，所以修改的方式应该保留最后的重试，而在前面建连成功的时，直接返回。感谢你提的 Bug，但是修复的方式应该兼具 Mesh与直连场景。

2019-02-22 15:53 UTC, idevz requested changes
https://github.com/weibocom/motan-openresty/blob/75db542d4a7564a2ddcf4cecf80cf212d1bb7121/lib/motan/endpoint/motan.lua#L72
可以在这里，当第一次建连成功时，直接返回，避免后面的重复建连

2019-02-22 15:53 UTC, idevz commented on lib/motan/endpoint/motan.lua
> -    return sock:connect(self.url.host, self.url.port)
非 Mesh 场景下，当连接失败时，需要再次重试

2019-02-23 02:22 UTC, yangjian5 commented on lib/motan/endpoint/motan.lua
> -    return sock:connect(self.url.host, self.url.port)
明白了， 已经修改了

2019-02-23 02:58 UTC, idevz commented on lib/motan/endpoint/motan.lua
> -    return sock:connect(self.url.host, self.url.port)
cool :)

2019-02-23 03:00 UTC, idevz commented on lib/motan/endpoint/motan.lua
>          ngx.log(ngx.ERR, "socket connection error")
这句就不需要了，判断如果成功，直接返回，如果失败，就走后面的逻辑

2019-02-23 03:01 UTC, idevz approved these changes

2019-02-23 03:01 UTC, merged